import { useEffect, useState } from "react";
import { Alert } from "@openai/apps-sdk-ui/components/Alert";
import { Badge } from "@openai/apps-sdk-ui/components/Badge";
import { Button } from "@openai/apps-sdk-ui/components/Button";
import { Input } from "@openai/apps-sdk-ui/components/Input";
import type { AppErrorData, AutomationRule, AutomationRunRecord, BucketItem } from "../../../shared/contracts";
import { useAppState } from "../../context/app-state";
import { errorData, unwrap } from "../../lib/ipc";
import { ErrorPanel } from "./error-panel";
import { Modal } from "./modal";

const draft = () => ({ name: "After upload", bucket: "", prefix: "", enabled: true, notify: true, copyLink: "none" as AutomationRule["copyLink"], expiresInSeconds: 3600, copyToBucket: "", copyToPrefix: "" });
export const AutomationDialog = ({ open, onClose }: { open: boolean; onClose: () => void }) => {
  const { activeProfile, bootstrap, tx } = useAppState();
  const zh = bootstrap?.preferences.locale === "zh-CN";
  const [rules, setRules] = useState<AutomationRule[]>([]);
  const [runs, setRuns] = useState<AutomationRunRecord[]>([]);
  const [buckets, setBuckets] = useState<BucketItem[]>([]);
  const [form, setForm] = useState(draft);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<AppErrorData | null>(null);
  const load = async () => {
    if (!activeProfile) return;
    setBusy(true);
    try { const [ruleResult, runResult, bucketResult] = await Promise.all([window.r2.automation.list({ profileId: activeProfile.id }), window.r2.automation.runs({ profileId: activeProfile.id }), window.r2.buckets.list(activeProfile.id)]); setRules(unwrap(ruleResult)); setRuns(unwrap(runResult)); setBuckets(unwrap(bucketResult)); setError(null); }
    catch (problem) { setError(errorData(problem)); } finally { setBusy(false); }
  };
  useEffect(() => { if (open) void load(); }, [open, activeProfile?.id]);
  if (!activeProfile) return null;
  const save = async () => { setBusy(true); try { unwrap(await window.r2.automation.save({ ...form, profileId: activeProfile.id, copyToBucket: form.copyToBucket || undefined })); setForm(draft()); await load(); } catch (problem) { setError(errorData(problem)); } finally { setBusy(false); } };
  const toggle = async (rule: AutomationRule) => { const { createdAt: _created, updatedAt: _updated, ...input } = rule; unwrap(await window.r2.automation.save({ ...input, enabled: !rule.enabled })); await load(); };
  return <Modal open={open} onClose={onClose} title={tx("Upload automation")} description={tx("Rules run after a verified upload. Conversion and naming remain previewable upload-plan steps; these rules handle copy, link, and notification actions.")}><div className="space-y-5">
    {error ? <ErrorPanel error={error} /> : null}
    <Alert color="info" title={tx("Failure-safe sequencing")} description={tx("The uploaded source is kept if an automation fails. The transfer becomes Partial success and records the exact failed rule.")} />
    <div className="grid gap-2 sm:grid-cols-2"><Input value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} placeholder={tx("Rule name")} /><select className="h-8 rounded-lg border border-default bg-surface px-2 text-sm" value={form.bucket} onChange={(event) => setForm((current) => ({ ...current, bucket: event.target.value }))}><option value="">{tx("Source bucket")}</option>{buckets.map((bucket) => <option key={bucket.name} value={bucket.name}>{bucket.name}</option>)}</select><Input value={form.prefix} onChange={(event) => setForm((current) => ({ ...current, prefix: event.target.value.replace(/^\/+/, "") }))} placeholder={tx("Match key prefix (empty = all)")} /><select className="h-8 rounded-lg border border-default bg-surface px-2 text-sm" value={form.copyLink} onChange={(event) => setForm((current) => ({ ...current, copyLink: event.target.value as AutomationRule["copyLink"] }))}><option value="none">{tx("Do not copy a link")}</option><option value="temporary">{tx("Copy 1-hour temporary link")}</option><option value="public">{tx("Copy permanent public URL")}</option></select><select className="h-8 rounded-lg border border-default bg-surface px-2 text-sm" value={form.copyToBucket} onChange={(event) => setForm((current) => ({ ...current, copyToBucket: event.target.value }))}><option value="">{tx("No remote copy action")}</option>{buckets.map((bucket) => <option key={bucket.name} value={bucket.name}>{zh ? `复制到 ${bucket.name}` : `Copy into ${bucket.name}`}</option>)}</select><Input value={form.copyToPrefix} onChange={(event) => setForm((current) => ({ ...current, copyToPrefix: event.target.value.replace(/^\/+/, "") }))} placeholder={tx("Copy destination prefix")} /></div>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.notify} onChange={(event) => setForm((current) => ({ ...current, notify: event.target.checked }))} />{tx("Show completion notification")}</label>
    {form.bucket ? <Alert color="warning" title={tx("Simulation — no remote action has run")} description={zh ? `匹配 r2://${form.bucket}/${form.prefix} 的已验证上传将${[form.copyToBucket ? `复制到 ${form.copyToBucket}/${form.copyToPrefix}` : "", form.copyLink !== "none" ? `复制 ${form.copyLink === "temporary" ? "临时" : "永久公开"}链接` : "", form.notify ? "显示通知" : ""].filter(Boolean).join("，然后") || "不执行动作"}。每个动作都有检查点，重试不会重复已完成动作。` : `A verified upload matching r2://${form.bucket}/${form.prefix} would ${[form.copyToBucket ? `copy to ${form.copyToBucket}/${form.copyToPrefix}` : "", form.copyLink !== "none" ? `copy a ${form.copyLink} link` : "", form.notify ? "show a notification" : ""].filter(Boolean).join(", then ") || "do nothing"}. Each action is checkpointed so a retry does not repeat completed actions.`} /> : null}
    <div className="flex justify-between gap-2">{rules.some((rule) => rule.enabled) ? <Button color="warning" variant="ghost" onClick={async () => { if (!window.confirm(tx("Pause every enabled automation rule for this connection?"))) return; setBusy(true); try { for (const rule of rules.filter((item) => item.enabled)) { const { createdAt: _created, updatedAt: _updated, ...input } = rule; unwrap(await window.r2.automation.save({ ...input, enabled: false })); } await load(); } catch (problem) { setError(errorData(problem)); } finally { setBusy(false); } }}>{tx("Pause all rules")}</Button> : <span />}<Button color="primary" loading={busy} disabled={!form.name || !form.bucket || (!form.notify && form.copyLink === "none" && !form.copyToBucket)} onClick={() => void save()}>{tx("Create rule")}</Button></div>
    <div className="max-h-72 space-y-2 overflow-auto">{rules.map((rule) => <div key={rule.id} className="rounded-xl border border-subtle p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{rule.name} <Badge color={rule.enabled ? "success" : "secondary"}>{tx(rule.enabled ? "Enabled" : "Paused")}</Badge></p><p className="mt-1 text-xs text-secondary">r2://{rule.bucket}/{rule.prefix} · {rule.copyToBucket ? `${zh ? "复制到" : "copy to"} ${rule.copyToBucket}/${rule.copyToPrefix ?? ""} · ` : ""}{rule.copyLink !== "none" ? `${rule.copyLink} ${zh ? "链接" : "link"} · ` : ""}{rule.notify ? tx("notify") : ""}</p></div><div className="flex gap-1"><Button color="secondary" variant="outline" size="xs" onClick={() => void toggle(rule)}>{tx(rule.enabled ? "Pause" : "Enable")}</Button><Button color="danger" variant="ghost" size="xs" onClick={async () => { if (window.confirm(zh ? `删除自动化规则 ${rule.name}？` : `Delete automation ${rule.name}?`)) { unwrap(await window.r2.automation.delete(rule.id)); await load(); } }}>{tx("Delete")}</Button></div></div></div>)}</div>
    <details className="rounded-xl border border-subtle p-3"><summary className="cursor-pointer text-sm font-medium">{tx("Recent automation action log")} · {runs.length}</summary>{runs.length ? <div className="mt-3 max-h-64 space-y-2 overflow-auto">{runs.slice(0, 100).map((run) => { const rule = rules.find((item) => item.id === run.ruleId); return <div key={`${run.eventId}:${run.ruleId}`} className="rounded-lg bg-surface-secondary p-2"><div className="flex items-center justify-between gap-2"><p className="truncate text-xs font-medium">{rule?.name ?? run.ruleId}</p><Badge size="sm" color={run.failures.length ? "warning" : "success"}>{run.failures.length ? tx("Needs attention") : tx("Checkpointed")}</Badge></div><p className="mt-1 truncate font-mono text-[11px] text-secondary">{run.bucket && run.key ? `r2://${run.bucket}/${run.key}` : run.eventId.slice(0, 16)}</p><p className="mt-1 text-[11px] text-tertiary">{new Date(run.updatedAt).toLocaleString(zh ? "zh-CN" : "en")} · {run.actions.length ? run.actions.join(" → ") : tx("No action completed")}</p>{run.failures.map((failure) => <p key={failure} className="mt-1 text-[11px] text-warning">{failure}</p>)}</div>; })}</div> : <p className="mt-3 text-xs text-secondary">{tx("No automation has run yet.")}</p>}</details>
    <div className="flex justify-end"><Button color="secondary" variant="outline" onClick={onClose}>{tx("Close")}</Button></div>
  </div></Modal>;
};
